language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "S/1dy35nT16J3dUz6jKwM8ODcewhJg/WRsBsIKOep4fBYVabQ1pMZtIklvDOSJbphXZKCWBhH/fu139lqpX4nwz0Ouse0fm9dvZALqrRaeJUl5K1PQXlS+NlNOlOT30AbJRR8KvsdfkFao8FdfydnvVLxV2pOYs0Fw1lUcLVUjrgPOtbTZmYva5QWbRByAn0bbOeaxFi7WTVs6+mjDiJIjbnH3KCZbHzNmKId2utn+a5p4q2sU235T/4ZxFsDuAom6rgiQsS+9QALZyvJhnpTSO5PQ8VqtfljJt4BKFXez2MmoC2HjqetHekzYtAdbom+09XFQnD5JGYNpOV3mAideUxTJxOmPupIKkVf4YxdvAU9iyK0DfU5FK50+P70U82vCvY/A75QWHG+aKFpcxAmu1cFaK5NTfVHxmMpzJO33fMM+4VzHEQEvhosw2zlvGhHYGnTZ+PXvhiv5RKMEAfX/OCwyPUitL8vu4d6N3EdU95yGPutYD7ue11OHcI8KMjorOCJr7FPR+A9v65i8ZLovjmXqW34swfGynPADlQeDIlsI9W2wW0Nay4mnQzaspPrnApPSDW6Fjm/Yqa1QdcRVnJJ+03YrUlyZ0KmK4NDIuHBTmoNovXx8Izlq78dIDs8pjCdvs8hDdiFSjgWWTgQOT30Biu3RLT35wazrsIksc="
  secret_access_key:
    secure: "j2aYlZSlwVAS4/Q2j4gmeN/V5opOMhKjAxmCTh4EzrXYg2QQNxLg3QkuOs1BmgtwdE7x8qAbxib+Z5DEmeMtfaeF/lYZHdME+mFzuWK+2XeewJTgGxb1K8o2oq/YiUxjMWEPFW84I7/FYlyVlEQNVsSeEigmOCu0xjjFgdNQMpUXwDKaIBbMI/vWq8Xr5yQbU5ocP1exPgPHFpPPnNS6FHUThHQCXvGxQdvh0jBuW/utDSpYPWqdzlUjQkugnoHvU34KBTZfQJQ2Oz8DgubJBZILjfOgs4tMxnGs93aQThu/DzWO5zmLA6kEC7kBb0BGHrOr2mTzRAN1Mu2BUwWJPp+g2Pr6Pm/MUW05YrAy6rb7jKBGVWokGQ0rg8FbmWAvG9aT7Dj8sJWoHBSNjTmP/kkjJ/ZrTFwQIgcGW2Qpe129tdR4YiuAYg0wTLhKqGb3iyhNh283+1nZPuDUEjHATy5jdrNTXLnQ1Tqa7KPnsAo2Ug6OwyX3wG2GTBTeWps3yoBXqzzuKs6QH4ds+1ZCuiSW6t/rGrHJXXgASu/Oc9prNmEb7vX2wKUHn7M0Syl11gqapTh6PgQEM1NNo8zFRufB6dxjmAHcojudufhOVKvSceCZ08lcVwnYuQZpC49iRAdWEEZWBd8JBVxtd0DMQMT+bNRk0VLHuMuwtfeVny0="
  bucket: cc.andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  #upload_dir: .
